# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-03 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0299_auto_20250113_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='exempt_from_radius_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
