# Generated by Django 5.2.10 on 2026-06-08 02:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0308_proposaltype_add_to_proposal_type_section_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='help_text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
