# Generated by Django 5.2.10 on 2026-06-08 03:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0309_alter_globalsettings_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
