# Generated by Django 5.2.10 on 2026-06-08 04:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0310_alter_helppage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text_assessor',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
