# Generated by Django 5.2.10 on 2026-06-08 07:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0311_alter_masterlistquestion_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
