# Generated by Django 5.2.17 on 2026-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0316_seed_globalsettings_max_upload_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('assessment_reminder_days', 'Assessment reminder days'), ('das_sharepoint_page', 'DAS Sharepoint page'), ('proposal_assess_help_page', 'DAS Proposal assess help page'), ('compliance_assess_help_page', 'DAS compliance assess help page'), ('referral_assess_help_page', 'DAS referral assess help page'), ('proposal_approver_help_page', 'DAS Proposal approver help page'), ('shapefile_info', 'Shapefile further information'), ('proposal_type_help_url', 'Proposal Type help url'), ('region_help_url', 'Region help url'), ('district_help_url', 'District help url'), ('activity_type_help_url', 'Activity type help url'), ('sub_activity_1_help_url', 'Sub activity 1 help url'), ('sub_activity_2_help_url', 'Sub activity 2 help url'), ('category_help_url', 'Category help url'), ('max_no_polygon', 'Maximum number of polygons allowed in the Shapefile'), ('allowed_file_extensions', 'Allowed File Extensions (Standard)'), ('allowed_gis_archive_extensions', 'Allowed GIS Archive Extensions'), ('max_file_upload_size_mb', 'Maximum File Upload Size (MB)'), ('max_file_upload_size_mb_internal', 'Maximum File Upload Size for Internal Users (MB)')], max_length=255, unique=True),
        ),
    ]
